CREATE Database PodporinProcedure;
use PodporinProcedure;


create table preview (
	filmNimetus VARCHAR(50),
	last_name INT,
	rezisoor VARCHAR(50),
	v_aasta VARCHAR(50)
);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Exorcist, The', 56, 'Flin Clemens', 1998);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Three Guys Named Mike', 15, 'Bernadene McQuaide', 2008);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Sasha (Sascha)', 80, 'Ram Farmer', 1983);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Deadly Prey', 18, 'Caryl Castellini', 2005);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Net Worth', 3, 'Rikki Harlett', 1994);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('God''s Sandbox (Tahara)', 72, 'Angele Sine', 1994);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Aziz Ansari: Live at Madison Square Garden', 77, 'Lemmy Mangin', 2004);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Broken English', 74, 'Valerye Pickance', 2010);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Goddess of 1967, The', 75, 'Kira Ferrarini', 2000);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Devdas', 84, 'Wolf Sebyer', 1994);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Jerky Boys, The', 74, 'Bibi Kordes', 2009);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Violent Men, The', 58, 'Balduin McGucken', 1995);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('1911 (Xinhai geming)', 100, 'Antonina Farnfield', 1992);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Christopher Strong', 78, 'Elonore McClure', 1998);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Plaisir, Le', 98, 'Jeanette Reagan', 1995);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Longtime Companion', 19, 'Kippie Symcoxe', 2000);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Bandits', 39, 'Jamaal Zywicki', 2006);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Battlestar Galactica: The Plan', 92, 'Graeme Crosskill', 2010);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Trotsky, The', 50, 'Sherwynd Upcott', 2004);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Doughboys', 91, 'Sax Linstead', 1983);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Carrie', 65, 'Bird Gudeman', 2006);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Stationmaster Is on Fire - The Movie, That Is!, The (Stinsen brinner... filmen alltså)', 47, 'Georgette Gorrick', 1996);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Jungle de Ikou (Jungre de Ikou)', 6, 'Mara Halpen', 2010);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('AmericanEast', 83, 'Trip Absalom', 2009);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('The Trip to Squash Land', 46, 'Archibald Spiteri', 2009);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Sansho the Bailiff (Sanshô dayû)', 53, 'Libby St. Quintin', 2009);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Wrecked', 30, 'Jaquenette McGrayle', 1971);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Árido Movie', 21, 'Gregory Train', 2010);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Threesome', 35, 'Merrel Woodington', 1993);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Hooper', 6, 'Jilly Schouthede', 2012);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('I Love You, I Love You (Je t''aime je t''aime)', 75, 'Anabal Welfare', 1994);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Kill by Inches', 21, 'Karia Tomkiss', 1993);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Drop Dead Gorgeous', 80, 'Jaye Huckle', 1992);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Broadway Melody, The', 48, 'Hastie Ferruzzi', 1998);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Sebastian', 29, 'Gilberte Reeme', 1996);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Free The Mind', 87, 'Dallas Powlett', 2009);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Northwest', 42, 'Joana Winser', 2003);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Bedknobs and Broomsticks', 36, 'Elita Bonhome', 2003);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Riders', 63, 'Barbara Mantle', 1990);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Greenwich Village: Music That Defined a Generation ', 88, 'Arlina Leppington', 1995);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Man on a Mission: Richard Garriott''s Road to the Stars', 58, 'Aland Ledingham', 1987);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Cyrus', 99, 'Lodovico Baskerfield', 1964);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Ghost in the Machine (a.k.a. Deadly Terror)', 65, 'Mirabelle Donati', 1990);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Brown Sugar', 42, 'Roberto Pickerin', 1992);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Floating Skyscrapers', 19, 'Tabor Pace', 2001);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Divine Madness!', 12, 'Millard Dowyer', 1997);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('OH in Ohio, The', 55, 'Arron Senechault', 2006);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Train of Shadows (Tren de sombras)', 16, 'Arvin le Keux', 2010);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Nobody Owns Me (Mig äger ingen)', 32, 'Orland Benian', 2011);
insert into preview (filmNimetus, last_name, rezisoor, v_aasta) values ('Intact (Intacto)', 2, 'Filberte Enriquez', 2006);


select * from film;
--filmiNimetus otsing esimese täha järgi
create Procedure otsing1Taht
@taht char(1)
as
begin
	select * from film
	where filmNimetus LIKE concat (@taht, '%');
end;
--käivitamine
exec otsing1Taht 'F';


--protseduur mis kustutab sissetatus id gärgi
create Procedure kustutaFilm
@id int
as
begin
select  * from film;
delete from film where filmId=@id;
select * from film;
end;

exec kustutaFilm 42;

--procedur, mis loed filmide arv kokku

create Procedure FilmideArv
as
select count(*) as 'filmide Arv'from film;

exec FilmideArv;

--proceduur mis täidab tabeli film
create Procedure lisaFilm
@uusfilm varchar(50),
@kestvus int,
@rezisoor varchar(50),
@aasta int
as
begin
insert into film (filmNimetus, kestvus, rezisoor, v_aasta)
values (@uusfilm,@kestvus ,@rezisoor ,@aasta );
select * from film;
end;
exec lisaFilm 'test', 222, 'test', 2000;

